import { AppProvider } from "./components/AppContext";
import { Roboto } from 'next/font/google';
import './globals.css';
import { Toaster } from "react-hot-toast";
import Header from "./components/layout/Navbar/Header";
import Footer from "./components/layout/Home/Footer";
import Forma from "./components/icons/Forma";
import Forma2 from "./components/icons/Form2";
import Navbar from "./components/layout/Navbar/Navbar";

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body className={`${roboto.className} overflow-x-hidden`}>
        <main className="max-w-7xl mx-auto p-4 overflow-x-hidden">
          <AppProvider>
            <Toaster />
            <Navbar />
            <div className="hidden sm:hidden md:block lg:block"><Forma /></div>    
            <div className="block sm:block md:hidden lg:hidden"><Forma2 /></div>   
            {children}
            <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
